In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as pd

items = ['레넥톤','쉔','카르마','베인','오른','오른','아칼리','아칼리']

In [8]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels=labels.reshape(-1,1)

encoder = LabelEncoder()
encoder.fit(items)
labels_data = encoder.transform(items)
print('인코딩 값', labels_data)
print('인코딩 클래스', encoder.classes_)
print('디코딩 원본', encoder.inverse_transform([3,1,3,2,1,4]))

인코딩 값 [0 2 5 1 4 4 3 3]
인코딩 클래스 ['레넥톤' '베인' '쉔' '아칼리' '오른' '카르마']
디코딩 원본 ['아칼리' '베인' '아칼리' '쉔' '베인' '오른']


In [9]:
labels = labels.reshape(-1,1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원핫 인코딩 데이터')
print(oh_labels.toarray())

print('원핫 인코딩 데이터 차원')
print(oh_labels.shape)

원핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
원핫 인코딩 데이터 차원
(8, 6)


In [13]:
import pandas as pd
df = pd.DataFrame({'LOL': ['레넥톤','쉔','카르마','베인','오른','오른','아칼리','아칼리']})
pd.get_dummies(df)

LOL_레넥톤  LOL_베인  LOL_쉔  LOL_아칼리  LOL_오른  LOL_카르마
0        1       0      0        0       0        0
1        0       0      1        0       0        0
2        0       0      0        0       0        1
3        0       1      0        0       0        0
4        0       0      0        0       1        0
5        0       0      0        0       1        0
6        0       0      0        1       0        0
7        0       0      0        1       0        0

In [17]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

print(train_array)
print(test_array)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
